name: Deploy API Worker

on:
  push:
    branches:
      - main
    paths:
      - 'api-worker/**'             # 监控 api-worker 目录
      - '.github/workflows/deploy-api-worker.yml' 
      - 'pnpm-lock.yaml'            # 监控根锁文件变化
      - 'package.json'              # 监控根 package.json
      # - 'packages/**'             # 如果有共享 packages 目录也监控

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy API Worker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # 使用 pnpm setup action
        with:
          version: latest # 使用最新版 pnpm
          run_install: false # 不自动运行 install

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 使用 Node 20
          cache: 'pnpm' # 启用 pnpm 缓存

      - name: Install Dependencies (Root + Workspace)
        run: pnpm install --frozen-lockfile # 在根目录运行一次 install

      # 不需要单独安装 wrangler 了，因为它现在是根目录的 devDependency

      - name: Deploy api-worker
        # 使用 pnpm --filter 来指定要执行命令的包
        run: pnpm --filter imgn-api-worker run deploy 
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
