name: Deploy Sync Worker

on:
  push:
    branches:
      - main
    paths:
      - 'sync-worker/**'            # 监控 sync-worker 目录
      - '.github/workflows/deploy-sync-worker.yml'
      - 'pnpm-lock.yaml'            # 监控根锁文件变化
      - 'package.json'              # 监控根 package.json
      # - 'packages/**'             # 如果有共享 packages 目录也监控

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Sync Worker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Dependencies (Root + Workspace)
        run: pnpm install --frozen-lockfile # 在根目录运行一次 install

      - name: Deploy sync-worker
        # 使用 pnpm --filter 来指定要执行命令的包
        run: pnpm --filter imgn-sync-worker deploy 
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
